# Classification using SpaCy

In [1]:
!pip install spacy

In [2]:
!python -m spacy download en

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/lib/python3.6/dist-packages/en_core_web_sm -->
/usr/local/lib/python3.6/dist-packages/spacy/data/en
You can now load the model via spacy.load('en')


In [3]:
!python -m spacy download en_core_web_sm

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')


### Bag of Words - The Simplest Word Embedding Technique

This is one of the simplest methods of embedding words into numerical vectors. It is not often used in practice due to its oversimplification of language, but often the first embedding technique to be taught in the classroom setting.

```
doc1 = "I am high"
doc2 = "Yes I am high"
doc3 = "I am kidding" 

```

In [4]:
from IPython.display import Image
Image(url= "https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/1.PNG", width=500, height=300)

### Bag of Words and Tf-idf 
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

tf–idf for “Term Frequency times Inverse Document Frequency

In [0]:
Image(url= "https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/2.PNG", width=600, height=600)

In [0]:
Image(url= "https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/3.PNG", width=600, height=200)

In [0]:
import spacy
from spacy import displacy

In [0]:
nlp = spacy.load('en_core_web_sm')

In [0]:
text = "Apple, This is first sentence. and Google this is another one. here 3rd one is"

In [0]:
doc = nlp(text)

In [9]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd one is

In [10]:
for token in doc:
    print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
one
is


In [0]:
sent = nlp.create_pipe('sentencizer')

In [0]:
nlp.add_pipe(sent, before='parser')

In [0]:
doc = nlp(text)

In [15]:
for sent in doc.sents:
    print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd one is


In [0]:
from spacy.lang.en.stop_words import STOP_WORDS

In [0]:
stopwords = list(STOP_WORDS)

In [19]:
print(stopwords)

['whither', 'anyway', 'should', 'though', 'under', 'such', 'amount', 'ten', 'almost', 'with', '‘d', "'ve", 'none', "'s", 'nothing', 'to', 'while', 'neither', 'six', "'ll", 'made', 'anywhere', '’m', 'were', 'somehow', 'seemed', 'his', "'m", 'become', 'else', 'every', 'back', 'once', 'one', 'really', 'those', 'well', 'third', 'behind', '’s', 'along', 'amongst', 'hers', 'than', 'when', 'keep', 'give', 'often', 'put', 'therein', 'used', 'forty', 'from', 'besides', 'it', 'somewhere', 'thereupon', '’d', 'this', 'ever', 'through', 'thereafter', 'beyond', 'within', 'five', 'are', 'myself', 'for', 'because', 'whole', 'all', 'any', 'wherever', 'each', 'now', 'where', 'there', 'whereafter', 'few', 'must', 'did', 'enough', 'make', 'most', 'since', 'empty', 'their', 'whenever', 'among', 'via', 'toward', '‘m', 'latterly', 'already', 'other', '‘ve', 're', 'themselves', 'further', 'becoming', 'hereby', 'the', 'i', 'although', 'became', 'either', 'show', '‘re', 'may', 'then', 'being', 'here', 'fifty', 

In [20]:
len(stopwords)

326

In [21]:
for token in doc:
    if token.is_stop == False:
        print(token)

Apple
,
sentence
.
Google
.
3rd


### Lemmatization 

In [0]:
doc = nlp('run runs running runner')

In [23]:
for lem in doc:
    print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner


### POS 

In [0]:
doc = nlp('All is well at your end!')

In [25]:
for token in doc:
    print(token.text, token.pos_)

All DET
is VERB
well ADV
at ADP
your DET
end NOUN
! PUNCT


In [26]:
displacy.render(doc, style = 'dep', jupyter=True)

### Entity Detection 

In [0]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

In [0]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [28]:
displacy.render(doc, style = 'ent',jupyter=True)

### Text Classification 

In [0]:
import pandas as pd

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [0]:
data_yelp = pd.read_csv('https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/yelp_labelled.txt', sep='\t', header = None)

In [32]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [0]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name

In [34]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [35]:
data_yelp.shape

(1000, 2)

In [0]:
data_amazon = pd.read_csv('https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/amazon_cells_labelled.txt', sep = '\t', header = None)
data_amazon.columns = columns_name

In [37]:
data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [38]:
data_amazon.shape

(1000, 2)

In [0]:
data_imdb = pd.read_csv('https://frenzy86.s3.eu-west-2.amazonaws.com/fav/nlp/imdb_labelled.txt', sep = '\t', header = None)

In [0]:
data_imdb.columns = columns_name

In [41]:
data_imdb.shape

(748, 2)

In [42]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [0]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [53]:
data.shape

(2748, 2)

In [45]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [46]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [47]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

### Tokenization 

In [0]:
import string

In [0]:
punct = string.punctuation

In [50]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [0]:
def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [54]:
text_data_cleaning("    Hello how are you. Like this video")

['hello', 'like', 'video']

### Vectorization Feature Engineering (TF-IDF) 

In [0]:
from sklearn.svm import LinearSVC

In [0]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()

In [0]:
X = data['Review']
y = data['Sentiment']

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [59]:
X_train.shape, X_test.shape

((2198,), (550,))

In [0]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [61]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7f46d5a30b70>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [0]:
y_pred = clf.predict(X_test)

In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.81      0.80       285
           1       0.79      0.75      0.77       265

    accuracy                           0.78       550
   macro avg       0.78      0.78      0.78       550
weighted avg       0.78      0.78      0.78       550



In [64]:
confusion_matrix(y_test, y_pred)

array([[232,  53],
       [ 66, 199]])

In [65]:
clf.predict(['Wow, this is amzing lesson'])

array([1])

In [66]:
clf.predict(['Wow, this sucks'])

array([0])

In [68]:
clf.predict(['Worth of watching it. Please like it'])

array([1])

In [69]:
clf.predict(['Loved it. amazing'])

array([1])